DROP TABLE IF EXISTS "indoinggris";
CREATE TABLE "indoinggris" ("_id" INTEGER(10) PRIMARY KEY  NOT NULL , "indo" VARCHAR(50), "inggris" VARCHAR(50));
INSERT INTO "indoinggris" VALUES(1,'kamu','you');
INSERT INTO "indoinggris" VALUES(2,'saya','I');
INSERT INTO "indoinggris" VALUES(3,'abadi','eternal');
INSERT INTO "indoinggris" VALUES(4,'lantai','floor');
INSERT INTO "indoinggris" VALUES(5,'apel','aple');
INSERT INTO "indoinggris" VALUES(6,'pisang','banana');
INSERT INTO "indoinggris" VALUES(7,'telur','egg');
INSERT INTO "indoinggris" VALUES(8,'abadi','eternal');
INSERT INTO "indoinggris" VALUES(9,'mengabdikan','to enternalize');
INSERT INTO "indoinggris" VALUES(10,'keabadian','eternity');
INSERT INTO "indoinggris" VALUES(12,'acara','jurijidtion,administration of jus tice');
INSERT INTO "indoinggris" VALUES(13,'adegan','csene,act');
INSERT INTO "indoinggris" VALUES(14,'aduh ah','alast');
INSERT INTO "indoinggris" VALUES(15,'agama','religion');
INSERT INTO "indoinggris" VALUES(16,'agar','so that');
INSERT INTO "indoinggris" VALUES(17,'ahli bahasa','linguist');
INSERT INTO "indoinggris" VALUES(18,'ahli bangunan','arciect');
INSERT INTO "indoinggris" VALUES(19,'ahli ibadah','pious');
INSERT INTO "indoinggris" VALUES(20,'ahli hukum','lawyer');
INSERT INTO "indoinggris" VALUES(21,'ahli waris','the heirs');
INSERT INTO "indoinggris" VALUES(22,'air','water');
INSERT INTO "indoinggris" VALUES(23,'kaya','rich');
INSERT INTO "indoinggris" VALUES(24,'edit','edit');
INSERT INTO "indoinggris" VALUES(25,'enteng','esay');
INSERT INTO "indoinggris" VALUES(26,'fajar','day break');
INSERT INTO "indoinggris" VALUES(27,'fosil','fossil');
INSERT INTO "indoinggris" VALUES(28,'gadis','virgin,meiden,girl');
INSERT INTO "indoinggris" VALUES(29,'gagak ','krow');
INSERT INTO "indoinggris" VALUES(30,'pintar','smart');
INSERT INTO "indoinggris" VALUES(31,'tampan','handsome');
INSERT INTO "indoinggris" VALUES(32,'berhenti','stop');
INSERT INTO "indoinggris" VALUES(33,'hari','dey');
INSERT INTO "indoinggris" VALUES(34,'hari besar ','past day');
INSERT INTO "indoinggris" VALUES(35,'hidung','nose');
INSERT INTO "indoinggris" VALUES(36,'hidup','lipe,liping,toliping');
INSERT INTO "indoinggris" VALUES(37,'hindar','noise');
INSERT INTO "indoinggris" VALUES(38,'hingga','so,until,as far as');
INSERT INTO "indoinggris" VALUES(39,'ide','idea');
INSERT INTO "indoinggris" VALUES(40,'ijazah','permision');
INSERT INTO "indoinggris" VALUES(41,'bagaimana','how');
INSERT INTO "indoinggris" VALUES(42,'bini muda','concubine,younger wife ,second wife');
INSERT INTO "indoinggris" VALUES(43,'bising ','bujing ,bustle,,noise,rutles');
INSERT INTO "indoinggris" VALUES(44,'bisu ','dumb');
INSERT INTO "indoinggris" VALUES(45,'membisu','to keep silent , ');
INSERT INTO "indoinggris" VALUES(46,'obat bius','an aesthetic ,apiote');
INSERT INTO "indoinggris" VALUES(47,'pisang','banana');
INSERT INTO "indoinggris" VALUES(48,'mangga','orange');
INSERT INTO "indoinggris" VALUES(49,'keluarga','pamily');
DROP TABLE IF EXISTS "inggrisindo";
CREATE TABLE "inggrisindo" ("_id" INTEGER(10) PRIMARY KEY  NOT NULL , "inggris" VARCHAR(50), "indo" VARCHAR(50));
INSERT INTO "inggrisindo" VALUES(1,'What','Apa');
INSERT INTO "inggrisindo" VALUES(2,'adlib','mendadak');
INSERT INTO "inggrisindo" VALUES(3,'administer','mengurus');
INSERT INTO "inggrisindo" VALUES(4,'advert','iklan');
INSERT INTO "inggrisindo" VALUES(5,'after','sebelum,kemudian');
INSERT INTO "inggrisindo" VALUES(6,'apection','cinta,perasaan gemarsksn');
INSERT INTO "inggrisindo" VALUES(7,'affair','urusan,perkara');
INSERT INTO "inggrisindo" VALUES(8,'afficianando','orang yang senang');
INSERT INTO "inggrisindo" VALUES(9,'affact','mempengaruhi');
INSERT INTO "inggrisindo" VALUES(10,'afternon ','sore,petang');
INSERT INTO "inggrisindo" VALUES(11,'bepore','sebelum');
INSERT INTO "inggrisindo" VALUES(12,'asset ','berharga,orang berguna');
INSERT INTO "inggrisindo" VALUES(13,'avocado','alpukat');
INSERT INTO "inggrisindo" VALUES(14,'axe','kapak');
INSERT INTO "inggrisindo" VALUES(15,'babe','bayi');
INSERT INTO "inggrisindo" VALUES(16,'back','belakang,punggung');
INSERT INTO "inggrisindo" VALUES(17,'back drop','latar belakang');
INSERT INTO "inggrisindo" VALUES(18,'backdown','kemunduran');
INSERT INTO "inggrisindo" VALUES(19,'bacon','lemak babi');
INSERT INTO "inggrisindo" VALUES(20,'bacerial','disebabkan oleh bakeri');
INSERT INTO "inggrisindo" VALUES(21,'bead','jelek,kurang baik');
INSERT INTO "inggrisindo" VALUES(22,'bilk','menipu');
INSERT INTO "inggrisindo" VALUES(23,'caaba ','kabah');
INSERT INTO "inggrisindo" VALUES(24,'cabby','supir taksi');
INSERT INTO "inggrisindo" VALUES(25,'cagey','cerdik');
INSERT INTO "inggrisindo" VALUES(26,'cake','kue');
INSERT INTO "inggrisindo" VALUES(27,'camera','kamera');
INSERT INTO "inggrisindo" VALUES(28,'car','mobil');
INSERT INTO "inggrisindo" VALUES(29,'cat ','kucing ');
INSERT INTO "inggrisindo" VALUES(30,'call','panggil');
INSERT INTO "inggrisindo" VALUES(31,'I','saya');
INSERT INTO "inggrisindo" VALUES(32,'city','kota');
INSERT INTO "inggrisindo" VALUES(33,'complate','sempurna');
INSERT INTO "inggrisindo" VALUES(34,'copy','kopi');
INSERT INTO "inggrisindo" VALUES(35,'dad ','ayah, bpak');
INSERT INTO "inggrisindo" VALUES(36,'dace ','sejenis ikan air tawar');
INSERT INTO "inggrisindo" VALUES(37,'dady','bapak');
INSERT INTO "inggrisindo" VALUES(38,'day','hari');
INSERT INTO "inggrisindo" VALUES(39,'death','kematian');
INSERT INTO "inggrisindo" VALUES(40,'dear','tercinta');
INSERT INTO "inggrisindo" VALUES(41,'deary','jantung hati');
INSERT INTO "inggrisindo" VALUES(42,'debut ','tindakan pertama');
INSERT INTO "inggrisindo" VALUES(43,'defacto','dalam kenyataan');
INSERT INTO "inggrisindo" VALUES(44,'defamation','fitnahan');
INSERT INTO "inggrisindo" VALUES(45,'dance','berdansa');
